name: dart_clojure
description: A Clojure core implementation in Dart.
version: 0.0.1
repository: https://github.com/ClojureWasm/dart_clojure

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
